# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: max_os/interfaces/grpc/protos/maxos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'max_os/interfaces/grpc/protos/maxos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)max_os/interfaces/grpc/protos/maxos.proto\x12\x05maxos\"}\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x30\n\x07\x63ontext\x18\x02 \x03(\x0b\x32\x1f.maxos.TextRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa3\x01\n\rAgentResponse\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x32\n\x07payload\x18\x04 \x03(\x0b\x32!.maxos.AgentResponse.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x0fOperationUpdate\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"\x96\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x33\n\x07metrics\x18\x03 \x03(\x0b\x32\".maxos.HealthResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xc8\x01\n\x0cMaxOSService\x12\x36\n\nHandleText\x12\x12.maxos.TextRequest\x1a\x14.maxos.AgentResponse\x12@\n\x10StreamOperations\x12\x12.maxos.TextRequest\x1a\x16.maxos.OperationUpdate0\x01\x12>\n\x0fGetSystemHealth\x12\x14.maxos.HealthRequest\x1a\x15.maxos.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'max_os.interfaces.grpc.protos.maxos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_TEXTREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_AGENTRESPONSE_PAYLOADENTRY']._loaded_options = None
  _globals['_AGENTRESPONSE_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_TEXTREQUEST']._serialized_start=52
  _globals['_TEXTREQUEST']._serialized_end=177
  _globals['_TEXTREQUEST_CONTEXTENTRY']._serialized_start=131
  _globals['_TEXTREQUEST_CONTEXTENTRY']._serialized_end=177
  _globals['_AGENTRESPONSE']._serialized_start=180
  _globals['_AGENTRESPONSE']._serialized_end=343
  _globals['_AGENTRESPONSE_PAYLOADENTRY']._serialized_start=297
  _globals['_AGENTRESPONSE_PAYLOADENTRY']._serialized_end=343
  _globals['_OPERATIONUPDATE']._serialized_start=345
  _globals['_OPERATIONUPDATE']._serialized_end=413
  _globals['_HEALTHREQUEST']._serialized_start=415
  _globals['_HEALTHREQUEST']._serialized_end=430
  _globals['_HEALTHRESPONSE']._serialized_start=433
  _globals['_HEALTHRESPONSE']._serialized_end=583
  _globals['_HEALTHRESPONSE_METRICSENTRY']._serialized_start=537
  _globals['_HEALTHRESPONSE_METRICSENTRY']._serialized_end=583
  _globals['_MAXOSSERVICE']._serialized_start=586
  _globals['_MAXOSSERVICE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
