# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from max_os.interfaces.grpc.protos import maxos_pb2 as max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in max_os/interfaces/grpc/protos/maxos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaxOSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleText = channel.unary_unary(
                '/maxos.MaxOSService/HandleText',
                request_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.SerializeToString,
                response_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.StreamOperations = channel.unary_stream(
                '/maxos.MaxOSService/StreamOperations',
                request_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.SerializeToString,
                response_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.OperationUpdate.FromString,
                _registered_method=True)
        self.GetSystemHealth = channel.unary_unary(
                '/maxos.MaxOSService/GetSystemHealth',
                request_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthRequest.SerializeToString,
                response_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthResponse.FromString,
                _registered_method=True)


class MaxOSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaxOSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleText': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleText,
                    request_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.FromString,
                    response_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.AgentResponse.SerializeToString,
            ),
            'StreamOperations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOperations,
                    request_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.FromString,
                    response_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.OperationUpdate.SerializeToString,
            ),
            'GetSystemHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemHealth,
                    request_deserializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthRequest.FromString,
                    response_serializer=max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maxos.MaxOSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maxos.MaxOSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaxOSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maxos.MaxOSService/HandleText',
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.SerializeToString,
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/maxos.MaxOSService/StreamOperations',
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.TextRequest.SerializeToString,
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.OperationUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maxos.MaxOSService/GetSystemHealth',
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthRequest.SerializeToString,
            max__os_dot_interfaces_dot_grpc_dot_protos_dot_maxos__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
